# Generated by Django 3.2.5 on 2022-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_user_userinfo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('sname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('contact', models.PositiveIntegerField()),
            ],
        ),
    ]
