# Generated by Django 3.2.5 on 2022-08-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_student1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student1',
            old_name='history',
            new_name='python',
        ),
    ]
