# Generated by Django 3.2.5 on 2022-08-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20220817_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student2',
            name='slug',
        ),
    ]
