# Generated by Django 3.2.5 on 2022-09-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_student2_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student1',
            name='dov',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='dur',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='python',
        ),
    ]
