# Generated by Django 3.2.5 on 2022-09-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20220901_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student1',
            name='time',
        ),
    ]
