# Generated by Django 3.2.5 on 2022-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(choices=[('1', 'maths'), ('2', 'physics'), ('3', 'computers')], default=1, max_length=40),
        ),
    ]
